- // MIR for `unreachable_direct` before GVN
+ // MIR for `unreachable_direct` after GVN
  
  fn unreachable_direct() -> ! {
      let mut _0: !;
      let _1: Never;
      let mut _2: ();
      scope 1 {
          debug x => _1;
      }
  
      bb0: {
-         StorageLive(_1);
-         StorageLive(_2);
-         _2 = ();
-         _1 = move _2 as Never (Transmute);
+         nop;
+         nop;
+         _2 = const ();
+         _1 = const () as Never (Transmute);
          unreachable;
      }
  }
  
